# Generated by Django 4.1.1 on 2023-01-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alerta', models.IntegerField()),
                ('fecha', models.DateField()),
                ('tipo_alarma', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ot_mecanicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitud', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_permiso', models.DateField()),
                ('motivo', models.CharField(max_length=50)),
            ],
        ),
    ]
