# Generated by Django 4.1.1 on 2023-01-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='n_bus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
