# Generated by Django 4.1.1 on 2023-01-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_solicitud_descripcion_alter_alerta_tipo_alarma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='id',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_solicitud',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
