# Generated by Django 4.1.1 on 2023-01-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_alerta_id_alter_alerta_id_alerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='checklist',
            fields=[
                ('id_check', models.AutoField(primary_key=True, serialize=False)),
                ('kilometraje', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
                ('neumaticos', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('correas', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('aceite', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('mangueras', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('direccion', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('liquido_frenos', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('pastillas', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('balatas', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('observaciones', models.CharField(max_length=300)),
            ],
        ),
    ]
