# Generated by Django 4.1.1 on 2023-01-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_ot_mecanicos_id_checklist_n_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='n_bus',
            field=models.BigIntegerField(),
        ),
    ]
