# Generated by Django 4.1.1 on 2023-01-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_checklist_n_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='fecha_registro',
            field=models.DateField(),
        ),
    ]
